version: '3.8'

services:
  postgres:
    restart: no
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
