version: '3'
services:
  redis:
    image: redis:latest
    restart: no
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  redis_data:
