version: "3.8"

services:
  kafka:
    build:
      context: ./_docker/kafka/
      dockerfile: Dockerfile
    image: fox20431/kafka:latest
    restart: no
    ports:
      - "9093:9093"
      - "9092:9092"
